version: '3'

services:
  app:
    image: node:14-alpine
    command: npm run start
    working_dir: /usr/local/server/
    restart: on-failure
    container_name: remember-me
    environment:
      PORT: 3000
      DB_HOST: db
      DB_DATABASE: remember-me
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - './:/usr/local/server/'
    ports:
      - '8000:3000'
  db:
    image: postgres:11.2
    container_name: db
    environment:
      POSTGRES_DB: remember-me
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 7575:5432

